spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: hohoco0701@gmail.com
    password: hoho0701!!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

---
spring:
  profiles:
    active: dev
---
