spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/todoit
    username: root
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  dump:
    sql:
      maxlinelength: 0
custom:
  secret: 'hellotodoit'
  path:
    upload-images: 'C:/Users/gojaebeom/Desktop/workspace/uploads'