spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: hohoco0701@gmail.com
    password: hoho0701!!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
mybatis:
  mapper-locations: mappers/**/*.xml
#  type-aliases-package: com.uahage.api.domain
  configuration:
    map-underscore-to-camel-case: true

---
spring:
  profiles:
    active: dev
---
