spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/todoit-v2
    username: root
    password: woqja5164!
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  dump:
    sql:
      maxlinelength: 0
custom:
  secret: 'hellotodoit'
  path:
    upload-images: 'C:/Users/User/Desktop/workspace/uploads'